In [3]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

In [8]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [11]:
print("Data types of all element of list is  :")
for i in list_:
    print(type(i))

Data types of all element of list is  :
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
print("Date type of all element of array_list:")
for i in array_list:
    print(type(i))

Date type of all element of array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [13]:
# Q.3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

In [14]:
array_list = np.array(object = list_ , dtype = int)

In [15]:
array_list

array([1, 2, 3, 4, 5])

In [16]:
print("Data types of all element of list is  :")
for i in list_:
    print(type(i))

Data types of all element of list is  :
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [19]:
print("Data types of all element of array_list is  :")
for i in array_list:
    print(type(i))
    

Data types of all element of array_list is  :
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [20]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [21]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [23]:
num_array.shape

(2, 3)

In [24]:
num_array.size

6

In [25]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.

In [26]:
np.random.randint(0,1,(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [28]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np